# Generated by Django 6.0.2 on 2026-02-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ниши')),
            ],
            options={
                'verbose_name': 'Ниша',
                'verbose_name_plural': 'Ниши',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100, unique=True, verbose_name='YouTube Channel ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название канала')),
                ('average_views', models.IntegerField(default=0, verbose_name='Средние просмотры')),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='main.niche', verbose_name='Ниша')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
    ]
