# Generated by Django 6.0.2 on 2026-02-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_channel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('views', models.IntegerField()),
                ('avg_at_moment', models.IntegerField()),
                ('score', models.FloatField()),
                ('published_at', models.DateTimeField()),
                ('thumbnail', models.URLField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_videos', to='main.channel')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
