# Generated by Django 6.0.2 on 2026-02-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foundvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundvideo',
            name='sample_size',
            field=models.IntegerField(default=0),
        ),
    ]
