# Generated by Django 6.0.2 on 2026-02-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_foundvideo_sample_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundRemovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bg_remover/input/')),
                ('result', models.ImageField(blank=True, null=True, upload_to='bg_remover/output/')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('completed', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
