# Generated by Django 6.0.2 on 2026-02-28 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_niche_update',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserNicheUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Использовано обновлений')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.niche', verbose_name='Ниша')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niche_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лимит обновления ниши',
                'verbose_name_plural': 'Лимиты обновлений ниш',
                'unique_together': {('user', 'niche')},
            },
        ),
    ]
