# Generated by Django 6.0.2 on 2026-02-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_userprofile_last_niche_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='niche_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='Лимит обновлений на одну нишу'),
        ),
    ]
