# Generated by Django 6.0.2 on 2026-02-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_niche_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernicheupdate',
            options={'verbose_name': 'Счетчик обновлений ниши', 'verbose_name_plural': 'Счетчики обновлений ниш'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.AlterField(
            model_name='usernicheupdate',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано попыток'),
        ),
        migrations.AlterField(
            model_name='usernicheupdate',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='niche_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='Доступно обновлений на одну нишу'),
        ),
    ]
