# Generated by Django 6.0.2 on 2026-02-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_channel_user_alter_channel_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundvideo',
            name='video_id',
            field=models.CharField(max_length=50),
        ),
    ]
