# Generated by Django 6.0.2 on 2026-02-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_foundvideo_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundvideo',
            name='video_type',
            field=models.CharField(choices=[('shorts', 'Shorts'), ('long', 'Long Video')], default='shorts', max_length=10),
        ),
    ]
