# Generated by Django 6.0.2 on 2026-02-28 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_foundvideo_video_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundremovaltask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача удаления фона', 'verbose_name_plural': 'Задачи удаления фона'},
        ),
        migrations.AddField(
            model_name='backgroundremovaltask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bg_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backgroundremovaltask',
            name='image',
            field=models.ImageField(upload_to='bg_remover/%Y/%m/%d/input/'),
        ),
        migrations.AlterField(
            model_name='backgroundremovaltask',
            name='result',
            field=models.ImageField(blank=True, null=True, upload_to='bg_remover/%Y/%m/%d/output/'),
        ),
    ]
