# Generated by Django 6.0.2 on 2026-02-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_backgroundremovaltask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='niche_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='Доступно обновлений на одну нишу'),
        ),
    ]
