# Generated by Django 6.0.2 on 2026-03-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_userprofile_niche_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niche',
            options={'permissions': [('can_add_niche', 'Может добавлять ниши')], 'verbose_name': 'Ниша', 'verbose_name_plural': 'Ниши'},
        ),
    ]
