# Generated by Django 6.0.2 on 2026-03-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_niche_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundvideo',
            options={'ordering': ['-score'], 'verbose_name': 'Найденные видео всех пользователей', 'verbose_name_plural': 'Найденные видео всех пользователей'},
        ),
    ]
