# Generated by Django 6.0.2 on 2026-03-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='row_count',
            field=models.IntegerField(default=0),
        ),
    ]
