# Generated by Django 6.0.2 on 2026-03-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_report_analysis_data_report_row_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
