import os
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


local=True

if not local:
    # --- НАСТРОЙКИ ДЛЯ AMVERA ---
    SECRET_KEY = os.getenv('SECRET_KEY')
    
    DEBUG = os.getenv('DEBUG')
    
    YT_API_KEY = os.getenv('YT_API_KEY')

    # На Amvera монтируем диск в /data
    PERSISTENT_DIR = '/data'
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(PERSISTENT_DIR, 'db.sqlite3'),
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }
    # Картинки должны лежать на внешнем диске, чтобы не удаляться
    MEDIA_ROOT = os.path.join(PERSISTENT_DIR, 'media')

else:
    # --- ЛОКАЛЬНЫЕ НАСТРОЙКИ ---
    SECRET_KEY = "123"
    DEBUG = True
    YT_API_KEY = ''

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    # Локально сохраняем в папку проекта
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- ОБЩИЕ НАСТРОЙКИ ---
ALLOWED_HOSTS = ['*']

# MEDIA_URL всегда должен начинаться и заканчиваться слешем
# Это ПУТЬ В БРАУЗЕРЕ (ссылка), а не папка на сервере
MEDIA_URL = '/media/' 

# Не забудь про STATIC_ROOT, если DEBUG=False
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Application definition

INSTALLED_APPS = [
    'django_apscheduler',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

STATIC_URL = 'static/'

# Это скажет Django искать статику в папке static в корне проекта
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

DATETIME_FORMAT = 'd.m.Y H:i:s'
TIME_FORMAT = 'H:i:s'

APSCHEDULER_DATETIME_FORMAT = "d.m.Y H:i:s"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # секунд

# Максимальное количество файлов в одном запросе (ставим 1000 вместо 100)
DATA_UPLOAD_MAX_NUMBER_FILES = 1000

#  максимальный размер всего запроса (500 МБ), 
# чтобы сервер не "ругался" на тяжелые пачки фото
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

CSRF_TRUSTED_ORIGINS = ['https://infografika-bombito.amvera.io']

WHITENOISE_MAX_AGE = 31536000